# Generated by Django 4.2.9 on 2024-02-02 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Sistema.persona')),
                ('materiaList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesorList', to='Sistema.materia')),
                ('registroAsistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.registroasistencia')),
            ],
            bases=('Sistema.persona',),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Sistema.persona')),
                ('paralelo', models.CharField(max_length=1)),
                ('materiaList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudianteList', to='Sistema.materia')),
            ],
            bases=('Sistema.persona',),
        ),
    ]
